### ISSUE TITLE
Arrange Icons on Desktop

### ISSUE THREAD

**Issue by frettijule** [openthinclient/os-core#27]
I have several icons in my desktop, which I prefer to have placed at specific locations on my desktop.
But after restart die Icons always arranged in named order. It is indifferent, if the option  "Keep Aligned" (right-click on desktop) is on or off.
In version 1.x of openthinclient it was possible to arrange the icons manually.

**Comment by jfrenzel** [comment]
Not relevant, won't be fixed.
